# Generated by Django 2.1.4 on 2018-12-29 03:38

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=24, unique=True, verbose_name='username')),
                ('last_name', models.CharField(max_length=24, verbose_name='名前\u3000姓（カナ）')),
                ('first_name', models.CharField(max_length=24, verbose_name='名前\u3000名（カナ）')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuperVisor',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Staff')),
                ('is_admin', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.staff',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('staff_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authentication.Staff')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('authentication.staff',),
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
